In [1]:
import pandas as pd
import numpy as np
from sklearn.utils import shuffle

from code_source.dataframe_prep import get_cols_names
from code_source import data_prep
from code_source import metrics
from code_source import learning

# dataframe preparation

In [2]:
data=pd.read_csv('data/Dataset/Dataset/Training/Features_Variant_1.csv', header=None).drop_duplicates()
data=get_cols_names(data)
data=data.drop(columns=['post_promotion']) #post promotion has only zero values we can drop this col because it isn't informative

# data preparation

In [3]:
#'page_cat' to dummy because it is a category
#data=pd.concat([data,pd.get_dummies(data['page_cat'], prefix='page_cat')], axis=1)
#data=data.drop(columns=['page_cat'])

In [4]:
#data shuffling
data=shuffle(data).reset_index(drop=True)

# learning

In [5]:
#set algo params:
lam=1e-2
gamma=0 #now we needn't it
terms_num=10000
max_iter=1

# Cross-val

In [6]:
data.iloc[:,:-1], mean, std =data_prep.normalize(data.iloc[:,:-1])

res=pd.DataFrame()

parts=range(1,6)
idxs=[round(data.shape[0]/5)*(i-1) for i in range(1,6)]
idxs.append(data.shape[0])

for part in parts:
    #separate dataset
    test_part=data[idxs[part-1]:idxs[part]]
    train_part=data.drop(data.index[idxs[part-1]:idxs[part]])

    #features normalization (xi-mean)/std_err:
    #train_part.iloc[:,:-1], mean, std=normalize(train_part.iloc[:,:-1])#fit and transform train
    #test_part.iloc[:,:-1]=normalize_with_params(test_part.iloc[:,:-1], mean, std) #transform test
    
    params=learning.gradient_descend(train_part, lam, gamma, terms_num, max_iter) #model    
    test_pred=learning.get_prediction(params[:-1],params[-1],test_part.iloc[:,:-1])
    RMSE=metrics.custom_RMSE(test_part['target'], test_pred, gamma, params[:-1])
    r2=metrics.custom_R2(test_part['target'], test_pred)
    params=np.insert(params, 0 , [RMSE,r2])
    res[part]=params

[18803  8857 24695 ... 11983  2484 23120]
<class 'numpy.ndarray'>
[ 2691  6331  3407 ...   825  7804 31238]
<class 'numpy.ndarray'>
[19052  7453  1101 ... 15506  7584 21164]
<class 'numpy.ndarray'>
[ 8322 16507 28786 ... 11341  7972  6180]
<class 'numpy.ndarray'>
Iterations number is:1
The maximum number of iterations was reached.
RMSE is:36.81781513063726
R2 is:-0.039378204470921885
[22731   513  6718 ...   937  2516  6403]
<class 'numpy.ndarray'>
[21037 17983 30359 ...  6853  6374  7520]
<class 'numpy.ndarray'>
[26324 29789  6434 ... 13341 32126 12528]
<class 'numpy.ndarray'>
[31103 10662 16142 ... 17567 28471 11939]
<class 'numpy.ndarray'>
Iterations number is:1
The maximum number of iterations was reached.
RMSE is:36.136964214861514
R2 is:-0.04111717232470169
[25471 11070 13859 ... 13954 31959  7443]
<class 'numpy.ndarray'>
[15897 25533 13534 ... 29877 10690  2877]
<class 'numpy.ndarray'>
[18006 17369   183 ... 24338  5050 30836]
<class 'numpy.ndarray'>
[19934  3072 12867 ... 18053

In [7]:
text_idxs=np.array(['w'+str(i) for i in range(1,res.shape[0]-2)])
text_idxs=np.append(text_idxs,'w0')
text_idxs=np.insert(text_idxs, 0, ['RMSE', 'r2'])
res.index=text_idxs

res['mean']=np.mean(res, axis=1)
res['std']=np.std(res.iloc[:,:-1], axis=1)

In [8]:
res

1          2          3          4          5       mean  \
RMS  33.694860  36.506905  37.509125  37.258516  35.965994  36.187080   
r2   -0.047789  -0.038695  -0.038091  -0.038637  -0.041692  -0.040981   
w1    0.000240  -0.001887  -0.000214  -0.002037  -0.001203  -0.001020   
w2   -0.001329   0.005172   0.001302   0.003731   0.007901   0.003355   
w3    0.001389   0.001397   0.006254  -0.001006   0.001241   0.001855   
w4   -0.000393  -0.004037  -0.005299  -0.000029  -0.001325  -0.002216   
w5    0.004368  -0.002059  -0.000146  -0.001466  -0.002001  -0.000261   
w6    0.002498   0.000727   0.001500  -0.004509  -0.000356  -0.000028   
w7    0.003506   0.001971   0.005221  -0.001840   0.003631   0.002498   
w8    0.002635   0.000520   0.004820  -0.001360   0.003150   0.001953   
w9    0.003723   0.002513   0.004440  -0.003858   0.003809   0.002125   
w10  -0.000011  -0.001145   0.000597  -0.000885  -0.001000  -0.000489   
w11   0.002004   0.004110   0.002745  -0.002218  -0.001873   0.000953   
w12   0.002452   0.003526   0.005296  -0.002093   0.003558   0.002548   
w13   0.002303  -0.001895   0.005227  -0.003345   0.002659   0.000990   
w14   0.002692   0.005713   0.004340  -0.002050   0.001878   0.002514   
w15  -0.000522  -0.001687  -0.000800  -0.000429  -0.001447  -0.000977   
w16   0.003415   0.002164   0.000025  -0.004620   0.002423   0.000681   
w17   0.003435   0.000390   0.006180  -0.001817   0.005510   0.002740   
w18   0.000670  -0.003710   0.000134  -0.001347  -0.000076  -0.000866   
w19   0.003919   0.001707   0.004605  -0.003624   0.006053   0.002532   
w20   0.003684  -0.001986   0.000015  -0.001378  -0.001914  -0.000316   
w21   0.002413   0.000714   0.001472  -0.004841  -0.000288  -0.000106   
w22   0.003454   0.002266   0.005309  -0.001747   0.003669   0.002591   
w23   0.002588   0.000659   0.005160  -0.001142   0.002848   0.002023   
w24   0.003697   0.002781   0.004309  -0.003937   0.003840   0.002138   
w25  -0.003489  -0.002119  -0.000160   0.005210  -0.003086  -0.000729   
w26   0.002137   0.004722   0.002648  -0.001987  -0.001353   0.001233   
w27  -0.000927   0.006730   0.000195  -0.001186  -0.002275   0.000507   
w28  -0.001223   0.001060   0.004431  -0.000396   0.000512   0.000877   
w29   0.003628   0.004791   0.005107  -0.002720   0.003930   0.002947   
w30   0.004576  -0.007175  -0.001110  -0.004017  -0.003287  -0.002203   
w31   0.002577  -0.003936  -0.002058   0.000274   0.002835  -0.000062   
w32   0.004300  -0.004716  -0.002569  -0.003574  -0.005949  -0.002502   
w33   0.004351  -0.007064  -0.001342  -0.003729  -0.003120  -0.002181   
w34  -0.001135   0.000336   0.000253   0.002921   0.006810   0.001837   
w35  -0.001959  -0.005008   0.003641  -0.003645  -0.001805  -0.001755   
w36  -0.000992  -0.004351   0.003705  -0.000865  -0.002137  -0.000928   
w37   0.000807  -0.000921  -0.001621  -0.001210  -0.002103  -0.001010   
w38  -0.007363   0.003753   0.000257   0.000050   0.002435  -0.000174   
w39  -0.000734  -0.000284  -0.000708  -0.005758   0.011208   0.000745   
w40  -0.001378  -0.002305   0.002154  -0.003040   0.000680  -0.000778   
w41   0.000117   0.003582   0.001780   0.000242  -0.006563  -0.000168   
w42  -0.000682  -0.000062   0.001057   0.004235  -0.002103   0.000489   
w43   0.000722   0.004339  -0.003441  -0.003168  -0.004733  -0.001256   
w44   0.001664  -0.000771  -0.004932   0.004092   0.005347   0.001080   
w45   0.000257  -0.004671   0.004093   0.002878  -0.002995  -0.000088   
w46  -0.000927   0.004824  -0.004631   0.001790  -0.002373  -0.000263   
w47  -0.001031   0.000495  -0.000374  -0.004152   0.000875  -0.000837   
w48   0.000179   0.004002  -0.000194  -0.003038   0.004652   0.001120   
w49  -0.000267  -0.002003   0.001824  -0.003312  -0.002440  -0.001240   
w50  -0.002623  -0.001778   0.002566   0.005080  -0.002062   0.000237   
w51   0.003961  -0.000343   0.000509   0.000758  -0.001200   0.000737   
w52   0.000724  -0.004999   0.000177   0.002626   0.002714   0.000248  